### ISSUE TITLE
Support for named arguments

### ISSUE THREAD

**Issue by theolivenbaum** [Cysharp/ZLogger#10]
Would be nice to have support for named arguments on the format method, without having to rewrite all log messages. I guess in a first pass, they could all be interpreted as incrementing argument numbers, as they're usually not repeated in the log message.

`````csharp
 //this works

Logger.ZLogInformation("Log value {0}", 1234);

 //this throws "Input string was not in a correct format." in Cysharp.Text.FormatParser.Parse
Logger.ZLogInformation("Log value {VALUE}", 1234);
`````

**Comment by neuecc** [comment]
It is called [Message Templates](https://messagetemplates.org/).
It bothered me, but I omit it.
Because we wanted to avoid being unable to use the implementation of [ZString](https://github.com/Cysharp/ZString/) and having multiple implementations, it is unsupported.

**Comment by theolivenbaum** [comment]
Ok makes sense. It seems like the normal Logging methods work fine (with the extra cost of allocations), so we'll manually update where needed to the new syntax. Thanks!
