### ISSUE TITLE
FormatException is thrown if the log message string contains "{".

### ISSUE THREAD

**Issue by mxProject** [Cysharp/ZLogger#11]
Hello @neuecc .

FormatException is thrown if the log message string contains "{".

Configure the console logger by calling the AddZLoggerConsole method.

> await MagicOnionHost.CreateDefaultBuilder()
>     .UseMagicOnion(options, new ServerPort("localhost", port, credentials))
>     .ConfigureLogging(logging => 
>     {
>         logging.ClearProviders();
>         logging.AddZLoggerConsole(options =>
>         {
>             options.EnableStructuredLogging = false;
>         }
>         );
>     }
>     )
>     .RunConsoleAsync().ConfigureAwait(false);

Outputs a string containing "{" to the logger.

> logger.ZLogInformation("{abc=1}");

FormatException is thrown.

> System.FormatException: Input string was not in a correct format.
>    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
>    at Cysharp.Text.FormatParser.Parse(ReadOnlySpan`1 format)
>    at Cysharp.Text.ZString.Utf8Format[T1](IBufferWriter`1 bufferWriter, String format, T1 arg1)
>    at ZLogger.Entries.FormatLogEntry`2.FormatUtf8(IBufferWriter`1 writer, ZLoggerOptions options, Utf8JsonWriter jsonWriter)
>    at ZLogger.AsyncStreamLineMessageWriter.WriteLoop()

**Comment by neuecc** [comment]
Thank you for reporting.
Currently Log(string msg) redirected to Log(format), which is causing an error.
I'll fix soon.

**Comment by neuecc** [comment]
Now I've releade `1.2.1` it includes this fix.

**Comment by mxProject** [comment]
Thanks @neuecc
