### ISSUE TITLE
Misuse

### ISSUE THREAD

**Issue by FoxTes** [Cysharp/ZLogger#129]
Hello @neuecc 
I have the following code:

```
var builder = WebApplication.CreateSlimBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddZLoggerConsole();
builder.Services.AddHostedService<StartupService>();

var app = builder.Build();
app.Run();

public class StartupService(ILogger<StartupService> logger) : IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken)
    {
        while (true) logger.ZLogInformation($"yeap");
    }

    public Task StopAsync(CancellationToken cancellationToken) => throw new NotImplementedException();
}
```

It causes a lot of allocations and memory leaks

![image](https://github.com/Cysharp/ZLogger/assets/55885862/cb2b4269-c165-44a7-a21a-9ee1ba19c072)

Unlike standard code:

```
var builder = WebApplication.CreateSlimBuilder(args);
builder.Logging.ClearProviders();
builder.Logging.AddConsole();
builder.Services.AddHostedService<StartupService>();

var app = builder.Build();
app.Run();

public class StartupService(ILogger<StartupService> logger) : IHostedService
{
    public Task StartAsync(CancellationToken cancellationToken)
    {
        while (true) logger.LogInformation($"yeap");
    }

    public Task StopAsync(CancellationToken cancellationToken) => throw new NotImplementedException();
}
```

![image](https://github.com/Cysharp/ZLogger/assets/55885862/047ea340-7698-4231-9b68-3a6fa8e17e00)

Where did I go wrong?

PS. .NET 8. ZLogger 2.0.0

**Comment by neuecc** [comment]
Currently, there are no limits on buffer-queue, so if log output is too fast (while(true)! ), the memory will continue to grow because the consuming side cannot keep up.

If the standard logger is used, wait or drop when the buffer-queue limit is reached (default is wait)
While waiting, the buffer will be successfully consumed and GC will be performed.

Adding buffer options (Grow (current/default), Wait, Drop) might be a good.

**Comment by hadashiA** [comment]
In #143, we added `ZLoggerOptions.FullMode`.

.Block or .Drop is used can be take care of memory usage. 


```cs
public enum BackgroundBufferFullMode
{
    /// <summary>
    /// Grow the queue. (default)
    /// </summary>
    Grow,

    /// <summary>
    /// Wait until there's more room in the queue.
    /// </summary>
    Block,
    
    /// <summary>
    /// Drop the overflowing log entry.
    /// </summary>
    Drop,
}
```

**Comment by FoxTes** [comment]
When should I expect a release?

**Comment by neuecc** [comment]
after reviewd #145, #147, It will probably be tomorrow.
