### ISSUE TITLE
Improvement: Add optional MessageCap

### ISSUE THREAD

**Issue by JKamsker** [Cysharp/ZLogger#131]
To prevent memory exhaustion, Channel.CreateBounded should be used [here](https://github.com/Cysharp/ZLogger/blob/ca3526dcfec23e46f7a400ebe7671fea2c737dbf/src/ZLogger/AsyncStreamLineMessageWriter.cs#L51) or optional enable able.

**Comment by neuecc** [comment]
will provides Grow(current/default), Wait, Drop options.

related: #129

**Comment by hadashiA** [comment]
Thanks for your suggestion.

In #143, we added `ZLoggerOptions.FullMode`.
Now available three options for this.
