### ISSUE TITLE
Possible symbol name collisions in generated code

### ISSUE THREAD

**Issue by ltrzesniewski** [Cysharp/ZLogger#139]
I noticed that the generator can use the wrong type in the emitted code when the enclosing namespace defines a `LogLevel` enum for instance:

![image](https://github.com/Cysharp/ZLogger/assets/7913492/970a8957-26e1-4899-bfa4-d5456a9308af)

This may also be caused by several other types such as `JsonEncodedText`, `Unsafe` or `EventId` for instance.

Adding `global::` with the full namespace everywhere would fix this, but I'm not sure if you want to do that given the chance for this problem to occur is quite low, so feel free to close this issue. I wanted to notify you just in case.

The problem can be bypassed by the user by generating the messages in a separate namespace.

**Comment by neuecc** [comment]
thanks for reporting, I'll check soon.

**Comment by hadashiA** [comment]
I have taken care of this issue  in #144.
We changed most of the conflict-prone symbols to fullname. (although it may not be perfect).
