### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by john-h-k** [Cysharp/ZLogger#14]
ZLogger can't be used in a strong named assembly right now which is very frustrating

**Comment by neuecc** [comment]
Which situation do you need it?
For .NET Core, the guidance is mentioned that not require strongly-signed.
https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md

**Comment by john-h-k** [comment]
I have a strong named assembly which I want to consume zlogger from

**Comment by neuecc** [comment]
I don't like strong names.
For that reason, I want a specific, strong reason.
Does your library have to be signed?
