### ISSUE TITLE
Add Intermediate String Interpolater

### ISSUE THREAD

**Issue by Reag** [Cysharp/ZLogger#146]
Disclaimer: I am not the strongest C# Developer, and mainly live in the Unity space.

As a Unity Team lead, I unfortunately have to make compromises to support legacy patterns. As such, I was hoping to use ZLogger to help me replace all our calls to Debug.Log with minimal disruption. As such, I came up with a simple pattern that looks something like this:

```
public static void LogTrace(this Component o, ref ZLoggerInterpolatedStringHandler message)
{
    Factory.CreateLogger(o.GetType()).ZLog(LogLevel.Trace, ref message);
}
```

so my junior developers could write something like this:

```
this.LogTrace($"Called Method {methodName}");
```

As expected, the C# string interpolation did not like this, as the higher level call has no reference to the logger factory reference. I know what I would do to fix this, create a intermediate interpolated string class that receives from the override method and then passes it to the factory, however my own C# development skills are not up to accomplishing this task to a satisfactory level.

Would it be possible to provide some intermediate class that can be used to send interpolated strings around various functions before they are logged? I could imagine having a method that picks from different factories depending on runtime configuration for logging. I believe that this capability to send interpolated strings through function calls would be very useful outside of my own use-case.

In addition, its very possible my design is flawed from the get go, and I am more than welcome to ideas on how to improve it, given the limitations I must abide by (Mainly, making it very user friendly for junior unity developers).

**Comment by hadashiA** [comment]
If you want to invoke logging with a static method, it would be easier to share a logger instance instead of redefining a method that takes a string interpolation as an argument.

```cs
YourLogHelper.Logger = Factory.CreateLogger("Global"); // maybe on initialization
YourLogHelper.Logger.ZLogInformation(...);
````

I think calling CreateLogger for log calls is too expensive.

ZLogger follows the interface of Microsoft.Extensions.Logging.
If you don't use DI, then one Logger may be enough.

> I know what I would do to fix this, create an intermediate interpolated string class that receives from the override method and then passes it to the factory ,

This is maybe possible. But it might be too complicated for our purposes.

ZLog requires a logger when invoked. So if you want to omit the logger argument, you would have to set the logger for each Handler.
Using global logger might be a good enough compromise.

```cs
[InterpolatedStringHandler]
public ref struct ZLoggerTraceWrapperHandler
{
    public ZLoggerInterpolatedStringHandler InnerHandler;.

    public ZLoggerTraceWrapperHandler(int literalLength, int formattedCount, object component)
    {
        InnerHandler = new ZLoggerInterpolatedStringHandler(literalLength, formattedCount, LogManager.GlobalLogger, LogLevel.Trace, out var enabled); }
    }
    
    public void AppendLiteral(string s)
    {
        InnerHandler.AppendLiteral(s); }
    }

    public void AppendFormatted<T>(T value, int alignment = 0, string? format = null, [CallerArgumentExpression("value")] string? argumentName = null)
    {
        InnerHandler.AppendFormatted(value, alignment, format, argumentName);
    }
    
    public void AppendFormatted<T>(Nullable<T> value, int alignment = 0, string? format = null, [CallerArgumentExpression("value")] string? argumentName = null)
        where T : struct
    {
        InnerHandler.AppendFormatted<T>(value, alignment, format, argumentName); }
    }
    
    public void AppendFormatted<T>((string, T) namedValue, int alignment = 0, string? format = null, string? _ = null)
    {
        AppendFormatted(namedValue, alignment, format); }
    }
}
```

**Comment by Reag** [comment]
Having looked over your reply, I can clearly see my initial design was flawed from the get go. As such, I have adjusted it somewhat. I built a simple codegen dll to inject

```
private static readonly Microsoft.Extensions.Logging.ILogger Logger =
    ZLog.GetLogger<CLASS_NAME>(PARAM);
```

into any class that implements the correct attribute, referencing our global logging factory, ZLog. The attribute contains a struct for PARAM that configures the logger for that particular unity class. However, this lead me to a new problem that seems very much related to this topic!

Because of how unity handles certain objects ToString methods, I wish to include them in the logs. As such, I built the following overrides for use in building header messages to the logs:

```
public static void Debug(this ILogger logger, Component o,
    string message, [System.Runtime.CompilerServices.CallerMemberName] string memberName = "")
{
    logger.Debug(o.ToString(), message, memberName);
}

[ZLoggerMessage(LogLevel.Debug, "{header}: Method {memberName}: {message}")]
private static partial void Debug(this ILogger logger, string header, string message, string memberName);
```

Performing 'o.ToString()' is required because simply trying to string interpolate with '"{o}: Method {memberName}: {message}"' causes the ZLoggerMessage code gen to fail. This is likely either a small bug in the code gen or a limitation caused by weirdness with unity internals.

My second question is this: Would it be possible to change the 'string message' component into some sort of interpolater handler to allow for zero allocation? Or, once again, is my design flawed from the get go D:?

**Comment by hadashiA** [comment]
Is this what you want to do?
- The log must be called in a static method
- The log must have the name of the class that called it.

If you want to get the memberName that called the log,
Just as of version 2.3.0, you can access it via `LogInfo.MemberName` and so on.
You can probably customize the formatetr to add this to the log header :)

> My second question is this: Would it be possible to change the 'string message' component into some sort of interpolater handler to allow for zero allocation?

Isn't this a bit much for our purposes?

There are two different styles of log invocation: the staticc method and the ILogger<TCategory> method of naming the logger.

ZLogger is the latter design, so providing the exact equivalent functionality as a static method seems a bit of a stretch.

If I have misunderstood something, you are welcome to point it out. If you have any specific feature suggestions, please let me know.
