### ISSUE TITLE
Add native CLEF format json logging support

### ISSUE THREAD

**Issue by Reag** [Cysharp/ZLogger#149]
It would be very useful to have a built in formatter to create the correct message templates for the [CLEF](https://clef-json.org/) format of JSON messages. Several logging applications expect to get CLEF format logs, and I think it would be a nice addition to prevent users from having to implement their own formatters to create the correct message templates.

The specific part that would need attention is the pseudo string interpolation used by the CLEF message template format, specified [here](https://messagetemplates.org/). Currently, the default behavior for a JSON log is fairly similar to this:
```
{"@t":"TIME","@l":"Information","Category":"MyWebProvider","@m":"Loaded 21 items out of 26 from remote server!","loaded":21,"total":26}
```

while the desired output would be this:
```
{"@t":"TIME","@l":"Information","Category":"MyWebProvider","@mt":"Loaded {loaded} items out of {total} from remote server!","loaded":21,"total":26}
```

**Comment by neuecc** [comment]
Could you modify JsonPropertyNames configuration?
https://github.com/Cysharp/ZLogger?tab=readme-ov-file#json

**Comment by neuecc** [comment]
Thank you, I understand.  
I think it's a good suggestion. We have the information internally, so I'll try to prepare a way to extract it!

**Comment by Reag** [comment]
Thank you! That would be most helpful, as I'm required to log to CLEF for the project I'm in charge of

**Comment by neuecc** [comment]
v2.4.0 supports Write/GetOriginalFormat feature.
This is the sample of custom formatter of CLEF.
https://github.com/Cysharp/ZLogger/blob/master/sandbox/ConsoleApp/SampleCustomFormatter.cs

**Comment by Reag** [comment]
I'm afraid that the sample provided doesn't appear to compile properly. It seems to be written for net8, which Unity does not support. As such, the references on lines 69 and 70 will not compile properly. In addition, IZLoggerEntry does not have an override for WriteOriginalFormat, so the cast in the entry does not work on unity's version of dotnet

**Comment by neuecc** [comment]
Thanks, but good point.
Perhaps ResetWrittenCount will not work in Unity and you can use Clear instead.
