### ISSUE TITLE
"System.Runtime.CompilerServices.Unsafe.dll" version clash

### ISSUE THREAD

**Issue by njannink** [Cysharp/ZLogger#15]
Maybe not really a ZLogger issue.

We use the native collections from the package _unity.collections_ and that package is already shipped with the "System.Runtime.CompilerServices.Unsafe.dll" but version 4.0.4.1 and ZLogger is shipped with version 4.0.6 hence the version clash. As far as I can see the only workaround would be to use ilmerge to merge the version shipped with ZLogger as internal dll. Or do you see another possible solution for this?

see also: https://answers.unity.com/questions/1697304/how-to-resolve-multiple-precompiled-assemblies-err.html

**Comment by neuecc** [comment]
move unity.collections sourcecode to under own assets and remove unity.collection's dll.
