### ISSUE TITLE
The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces  and 'netstandard'

### ISSUE THREAD

**Issue by Niek352** [Cysharp/ZLogger#162]
I Clone my project on another PC and have this issue.

> Library\PackageCache\com.cysharp.zlogger\Runtime\ZLoggerUnityDebugLoggerProvider.cs(147,92): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by neuecc** [comment]
may solve NuGetForUnity v4.1.1?
https://github.com/GlitchEnzo/NuGetForUnity/pull/641

**Comment by Niek352** [comment]
This was a test project and I broke it completely, so I can't try to test this solution now
