### ISSUE TITLE
How to use only ZLogger.Generator?

### ISSUE THREAD

**Issue by pairbit** [Cysharp/ZLogger#163]
Hello. It is prohibited to use the System.IO.Hashing library on our projects.

We only use ZLoggerMessageAttribute on the project, which does not require the use of ZLoggerInterpolatedStringHandler, MessageSequence and Hashing LiteralList.

My request is that you separate the projects and make ZLogger.Core with ZLogger.Generator and without InterpolatedStringHandler.

Thanks

**Comment by neuecc** [comment]
I see. 
However, the usage is a bit too specific, so it's not feasible to separate that part.

**Comment by pairbit** [comment]
OK, thank you. I tried.
