### ISSUE TITLE
Enum Formatting

### ISSUE THREAD

**Issue by kagerouttepaso** [Cysharp/ZLogger#164]
After updating Zlogger to version 2.x.x, Enum values are being formatted as their raw values.
Is there a way to log the defined string values?

``` cs
var value = SampleEnum.BBB;

// Zlogger 2.x.x
logger.ZLogInformation($"enumValue : {value}"); // enumValue: 1

// Zlogger 1.x.x
logger.ZLogInformation("enumValue : {0}", value); // enumValue: BBB

public enum SampleEnum
{
    AAA,
    BBB,
    CCC,
}
```

**Comment by neuecc** [comment]
Thank you.
This is unintended behavior and I will fix it immediately!

**Comment by kagerouttepaso** [comment]
Thanks a lot for the quick response and for being willing to fix the issue!
I'm really looking forward to the updated version with the fix.

**Comment by neuecc** [comment]
`v2.5.0` fixed this, thanks.
