### ISSUE TITLE
Additional information in InternalErrorLogger

### ISSUE THREAD

**Issue by briananderton-il** [Cysharp/ZLogger#17]
Would love to see additional information available in the InternalErrorLogger callback.   

Currently errors in a log entry, such as a string formatting issue, just give an exception message something like "System.IndexOutOfRangeException: Index was outside the bounds of the array.".  In addition, since the processing is being done asynchronously, the call stack of the exception has very little useful information.

So, any additional information that could be provided, such as the raw message before formatting, is critical in narrowing down which of thousands of log entries is the culprit for an internal error.

**Comment by neuecc** [comment]
Thanks, indeed.
I've changed to
`public Action<LogInfo, Exception>? InternalErrorLogger { get; set; }`.

**Comment by neuecc** [comment]
I've released `1.3.0`.
