### ISSUE TITLE
Log to multiple files

### ISSUE THREAD

**Issue by bugproof** [Cysharp/ZLogger#172]
How to set it up to have multiple log files? e.g. db.log for database operations and app.log for other? In serilog it's possible to do it with filters.

I think a separate custom `ILoggerProvider` would be needed that creates and caches a separate `FileStream` for each `categoryName` in `public ILogger CreateLogger(string categoryName)` ... 🤔

**Comment by neuecc** [comment]
filtering is provided by Microsoft.Extensions.Logging.

**Comment by bugproof** [comment]
Yes but you can't setup filtering per file.

This is what I mean:
https://stackoverflow.com/questions/28292601/serilog-multiple-log-files
