### ISSUE TITLE
Please add more logging providers like Azure Application Insigths or AWS Cloudwatch Logs

### ISSUE THREAD

**Issue by martonx** [Cysharp/ZLogger#175]
Please add more logging providers like Azure Application Insigths or AWS Cloudwatch Logs.
This is a showstopper for us move from Nlog to Zlogger.

**Comment by neuecc** [comment]
In modern times, it is common for some kind of pipeline (e.g. fluentd) to be used to send data from standard output.
ZLogger itself does not have such a specific sending provider by default.
However, there is no problem with creating your own.
