### ISSUE TITLE
How to log threadId?

### ISSUE THREAD

**Issue by nmosafi** [Cysharp/ZLogger#177]
Hi is there a way to log the id of the thread which is performing the logging? As the file writing is done in a separate thread, simply adding `Environment.CurrentManagedThreadId` to the string passed to `SetPrefixFormatter` doesn't work.

Thanks

**Comment by neuecc** [comment]
thank you for contirbute, I've released in 2.5.7.
(LogInfo.ThreadInfo is modified nullable to normal)
