### ISSUE TITLE
GitHub about corrections.

### ISSUE THREAD

**Issue by kmgallahan** [Cysharp/ZLogger#19]
The current GitHub About text for this repo reads:

> Zero Allocation Text/Strcutured Logger for .NET Core and Unity, built on top of a Microsoft.Extensions.Logging.

Should read: 

> Zero allocation text/structured logger for .NET Core and Unity, built on top of Microsoft.Extensions.Logging.

**Comment by neuecc** [comment]
I may fix it someday.
