### ISSUE TITLE
Dynamic Log Level

### ISSUE THREAD

**Issue by AbeHamade** [Cysharp/ZLogger#194]
Is there a way to change the log level dynamically at run time? Preferably without having to use IOptions with reload which would require writing to the appsettings file.

**Comment by neuecc** [comment]
You can pass LogLevel as an argument to ZLog, but is that what you mean?

**Comment by AbeHamade** [comment]
No, in a typical scenario I use DI to inject ZLog into my application and subsequent classes. I would configure ZLog providers, etc. at application startup, including the initial log level. While the application is running, I need to change the log level from say Information, to Trace. I would like ZLog to dynamically change in a programmatic manner. ZLog will do this if I use IConfiguration method with IOptions and alter the appsettings.xml file with a new LogLevel in which ZLog detects the file chnage and performs a reload and then updates the LogLevel. However, this method requires changing a physical file in which Microsoft does not provide any support to do at runtime, only reading the file. There is a way alter the file programmatically, but in my opinion, this is a bit of a hack. Hopefully, I have made the question clearer.

**Comment by neuecc** [comment]
I don't really understand it well.
I would appreciate if you could show me how to achieve this kind of functionality, even with pseudocode.
Also, it would be helpful if you could point me to any other loggers that implement similar functionality.

**Comment by AbeHamade** [comment]
Serilog has a nuget package that performs this task. It is called LoggingLevelSwitch.

Here is a link to some additional information that you should find useful in understanding the question.

[https://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/](https://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/)

**Comment by neuecc** [comment]
Is this it?
https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/LoggingLevelSwitch.cs

Are you saying that you're providing MinimumLevel as something that can be dynamically updated?
While Microsoft.Extensions.Logging has SetMinimumLevel, you're not satisfied with it being static, correct?
Well, this doesn't seem to be ZLogger's job.
Please explore whether Microsoft.Extensions.Logging can achieve that behavior, and if it can't, make a proposal to them.

**Comment by AbeHamade** [comment]
That is exactly what I am saying. Often a developer will find support libraries lacking. So they venture to do a better job and build a better mousetrap. Libraries are created with many features that you are missing from other libraries. This is why you created ZLog to begin with is it not? While this feature may fall under some other responsibility, it does not mean it cannot be implemented to fill a gap. In the exact same manner in which ZLog was created to fill the gap Microsoft has with their own logging implementation, not to mention countless other logger implementations. 

Your stance on this matter is understandable and I respect it. Just to be clear, this issue was more of a question on if there was a way to perform dynamic log level changing with ZLog and am I just missing it. The clear answer is there is not. 

I do love ZLogger and find it to be better than every other logger I have tried. Thank you for your feedback and Happy Holidays!

**Comment by neuecc** [comment]
Thank you!
Yes, I understand your suggestion, and I've gained a deeper understanding as well - I appreciate it!
Since ZLogger has a fundamental concept of being built on top of Microsoft.Extensions.Logging,
there are some constraints (while I have some concerns that the foundation isn't necessarily the best, I'm making efforts to bypass it where possible).
While it would have been nice if we could avoid this case in ZLogger, since basic filtering is done in MS.E.Logging, avoiding it would mean adding another layer of filtering system on the ZLogger side, which probably wouldn't improve things much.
