### ISSUE TITLE
DLL overlap with Unity packages

### ISSUE THREAD

**Issue by MostHated** [Cysharp/ZLogger#20]
Hey there,
    I wanted to give this a try but unfortunately, my project exploded with errors. 

The Unity package com.unity.collections already includes System.Runtime.CompilerServices.Unsafe.dll. I tried to see if deleting the one that is included with ZLogger might do the trick, but then it gave these errors:
```
Assembly 'Assets/Plugins/Microsoft.Extensions.Primitives.dll' will not be loaded due to errors:
Microsoft.Extensions.Primitives references strong named System.Runtime.CompilerServices.Unsafe in a different folder, versions has to match. Assembly references: 4.0.6.0 Found in project: 4.0.4.0.
```
Then there are many other similar ones:
```
Assembly 'Assets/Plugins/System.Threading.Tasks.Extensions.dll' will not be loaded due to errors:
System.Threading.Tasks.Extensions references strong named System.Runtime.CompilerServices.Unsafe in a different folder, versions has to match. Assembly references: 4.0.4.1 Found in project: 4.0.4.0.
```
It then just continues on:
![](https://i.imgur.com/DeURomz.png)

I am not 100% sure on this, but I believe if you make ZLogger into either an official Unity package, or an OpenUPM [(Some info on it here)](https://openupm.com/docs/adding-upm-package.html), this might be able to be avoided. I believe it lets you contain the dependencies within the package so they do not conflict.

Thanks,
-MH

**Comment by neuecc** [comment]
You should remove UnityCollection's it.
That means you have to extract the package once and include it in your Assets.
Unity says 
> System.Runtime.CompilerServices.Unsafe.dll is removed from Unity.Collections package (next release [0.11.0]).
