### ISSUE TITLE
Support for Unity 2019.4 possible or planned?

### ISSUE THREAD

**Issue by sirchadwick** [Cysharp/ZLogger#23]
I added this through openupm before realizing it specifies 2018.3 as the only version for it. It hangs upon import during I think the compilation.

**Comment by neuecc** [comment]
sorry, it is caused by dll import samples `ManagedDlls~`.
https://github.com/Cysharp/ZLogger/tree/master/src/ZLogger.Unity/Assets/Scripts/ZLogger/ManagedDlls~/Plugins
I'll remove it.
