### ISSUE TITLE
Deleting old rolling file logs

### ISSUE THREAD

**Issue by ShadowDancer** [Cysharp/ZLogger#24]
RollingFile should have limits, like last month, or 1gb max, to not drain disk space on customers machine. I think this is critical to have if this lib is meant to be used in production environments.

> The generated files will not be deleted. If you want to do a log rotation, please do it from outside.

I think this is not good way to deal with log rotation. Especially if you have something misbehaving (generating lots of logs), the only solution is to *react* before disk fills up. 

To solve this from outside it would be really hard to get right, as it cannot be just solved with cron job, it needs active monitoring and dealing with locked files, whereas log process already knows file masks and can correctly compute file sizes and stop logging when attempting to roll.

I think the right thing to do is stop logging, because if something is misbehaving and creating lots of log files probably cause of the problem is much more useful. If logger would remove younger logs, it could hide the cause of problem with lots of gibberish.

**Comment by neuecc** [comment]
A classic practice is to monitor it externally, which I believe is possible.
However, this is certainly cumbersome.
Shall we add a retainedFileCountLimit?

**Comment by flier268** [comment]
Any plan?

**Comment by PolarGoose** [comment]
I always thought that the RollingFile was a fancy trick for implementing a circular buffer. Otherwise, why not just print the logs into a single file?
I feel that deleting old files is a crucial feature of the RollingFile functionality. It can't be safely and reliably delegated to an external service.
