### ISSUE TITLE
Is it possible to add thread ID and call stack information to the log output format?

### ISSUE THREAD

**Issue by jacking75** [Cysharp/ZLogger#26]
Looking at the code, it seems that only the following information can be added to the log text, but I want to leave the thread ID and callstack information as well.

public readonly struct LogInfo
{
        public readonly string CategoryName;
        public readonly DateTimeOffset Timestamp;
        public readonly LogLevel LogLevel;
        public readonly EventId EventId;
        public readonly Exception? Exception;
}

**Comment by neuecc** [comment]
We don't want to add anything that would be a burden on performance.
Or, if you can get the IAsyncLogProcessor implemented, there may be some things you can take.
