### ISSUE TITLE
Structured logging for Unity

### ISSUE THREAD

**Issue by tom-willmowski** [Cysharp/ZLogger#28]
Is there any plan to add this in the future?
What is the problem with integrating structured logging in Unity?

**Comment by neuecc** [comment]
Structured logging is dependent on System.Text.Json but it is not supported Unity.
It might be able to do this by decouple it and make it compatible with Unity's JsonSerializer.

**Comment by tom-willmowski** [comment]
There could be problems with Dictionaries. Maybe it would be better to use newtonsoft json?
