### ISSUE TITLE
How to format log entry timestamp?

### ISSUE THREAD

**Issue by robertmircea** [Cysharp/ZLogger#31]
Is it possible to change the log's timestamp format for text logger?
Currently I am using:
```c#
var prefixFormat = ZString.PrepareUtf8<string, DateTime>("{0} [{1}] ");
options.PrefixFormatter = (writer, info) => prefixFormat.FormatTo(ref writer, ConvertLoggingLevel(info.LogLevel), info.Timestamp.DateTime.ToLocalTime());
```
and obtain the following output: 
```
DBUG [11/15/2020 01:22:30] Running ..........
```

but I would like a different date format like `dd-MM-YYYY HH:mm:ss.fff`

**Comment by robertmircea** [comment]
Bump

**Comment by neuecc** [comment]
https://github.com/Cysharp/ZLogger#format-and-datetime-handling
