### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [Cysharp/ZLogger#35]
Git tag: 1.4.0
The version of package.json: 1.3.0

Suggestion: bump the version and re-tag 1.4.0. Perhaps check the release pipelines/utils to make sure the version is aligned before creating a Git tag.

Refs https://openupm.com/packages/com.cysharp.zlogger/?subPage=pipelines

**Comment by neuecc** [comment]
thanks,I've released `1.4.1`, it has same tag and version.
