### ISSUE TITLE
Worker support?

### ISSUE THREAD

**Issue by empz** [Cysharp/ZLogger#42]
Is there a way to use ZLogger in the .NET 5-based worker service?

The readme says we need to use ConsoleFramework but isn't both ASP.NET and Console apps in NET 3.1+ use the same IHostBuilder supporting the same ConfigureLogging method?

**Comment by neuecc** [comment]
everything that run on .NET Generic Host.
This means that all frameworks that can use `ConfigureLogging` are supported.

**Comment by empz** [comment]
Yes, sorry, it was VS not picking up the nuget installed for some reason.
