### ISSUE TITLE
The Unity logger does not allow to provide a context object

### ISSUE THREAD

**Issue by VacuumBreather** [Cysharp/ZLogger#45]
Unity's Debug.Log methods allow the passing of a context GameObject. Whenever such a log message is clicked the appropriate object in the scene hierarchy is highlighted.
The current implementation of the Unity logger in ZLogger does provide and API to pass such a context.

**Comment by HitCache** [comment]
+1 it would be very useful to have this please

**Comment by HitCache** [comment]
Commenting to reopen, feels pretty important.

**Comment by hadashiA** [comment]
Unfortunately, it seems difficult to support.

Note:.
In ZLogger, the parameters passed to the logger are held by generics that exist for each number of parameters. Therefore, there is no way to transparently scan parameters on the UnityDebugLogProcessor side.
