### ISSUE TITLE
Ambiguous method call: GetTypeInfo(System.Type)

### ISSUE THREAD

**Issue by aschearer** [Cysharp/ZLogger#50]
Full error:
`UnityLoggerFactory.cs(200, 56): [CS0121] The call is ambiguous between the following methods or properties: 'System.Reflection.TypeExtensions.GetTypeInfo(System.Type)' and 'System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)'`

This is in Unity 2019.4.13f1 running .NET 4.x, using `ZLogger.Unity.1.6.0` and `ZString.Unity.2.4.2`.

**Comment by neuecc** [comment]
I can't reproduce it, have you installed other libs?
