### ISSUE TITLE
Format DateTime with custom format?

### ISSUE THREAD

**Issue by theolivenbaum** [Cysharp/ZLogger#9]
Hi @neuecc , awesome work on the library!

Just posting this here as something I noticed that is missing on the library... It seems like the formatter doesn't support DateTime formatting, like this for the PrefixFormatter:

````csharp
logging.AddZLoggerConsole(options => options.PrefixFormatter = (buf, info) => ZString.Utf8Format(buf, "[{0}] [{1:hh:mm:ss}]", info.LogLevel, info.Timestamp.LocalDateTime));
````

This works for now of course, but it doesn't add the leading 0 on the numbers:
````csharp
logging.AddZLoggerConsole(options => options.PrefixFormatter = (buf, info) => ZString.Utf8Format(buf, "[{0}] [{1}:{2}:{3}]", GetLogLevelString(info.LogLevel), info.Timestamp.LocalDateTime.Hour, info.Timestamp.LocalDateTime.Minute, info.Timestamp.LocalDateTime.Second));
`````

**Comment by richard-green** [comment]
I believe this limitation comes from ZString.Utf8Format

**Comment by neuecc** [comment]
Yes, it is StandardFormat's limitation.
I'ｍ already requested to dotnet/runtime.
https://github.com/dotnet/runtime/issues/28942

I'm hoping to improve it too, so please Up Vote.

**Comment by theolivenbaum** [comment]
Thanks @neuecc, will follow the issue there - meanwhile the [{1}:{2}:{3}] works fine for now, so feel free to close this issue if you want!

**Comment by neuecc** [comment]
@theolivenbaum 

> it doesn't add the leading 0 on the numbers:

StandardFormatter supports precision and it can use like `{0:D2}`.
I'll write to document.
